### PR TITLE
Remove scss extensions from @material/mdc-* imports

### PR DESCRIPTION
**Pull request by johnelliott**
Hi, I would like to help with material-components-web-react.

The sass imports are handy, but I was having trouble importing SCSS from Button. I needed to directly import the css from the non-react package, basically duplicating the intent of the index.scss of react-button:
image

When I looked at [the icon component sass import](https://github.com/material-components/material-components-web-react/blob/a45c75a1fd8bc7b83fbe0775fc629c928bb1df0f/packages/material-icon/index.scss#L2) I noticed that it didn't have an extension. Going into node_modules and removing it from the button index.scss file fixed the issue and allowed me to just import the button styles with `@import "@material/button/mdc-button";`, so perhaps this was just an oversight.

I've never used learn before, so I may need help figuring out how to contribute to this codebase :/

### CODE REVIEW

**Comment by johnelliott** [comment]
I signed it!

**Comment by moog16** [comment]
@johnelliott Thanks for opening the PR. You're right it's not necessary and we can remove the extension from the filename. Can you also remove it from card, floating-label, line-ripple, and text-field Sass files for consistency?

Also something I realize is that you do not have the creds for the screenshot tests. I pushed a commit to see if it works for me.

**Comment by johnelliott** [comment]
@moog16 thanks Matt. I like this lib; want to show my support :)

**Comment by johnelliott** [comment]
Is it OK to add line-ripple, floating-label to the allowed scopes for commit messages?

**Comment by johnelliott** [comment]
Perhaps this [test failure](https://github.com/material-components/material-components-web-react/pull/62l) is also permission related for the screenshot job.

**Comment by moog16** [comment]
RE allowed scopes: YES definitely

RE Testing: Looking into Docker. Might be able to help us here.

**Comment by johnelliott** [comment]
Ok, I use Docker and maybe that'd be the easiest way to get many people up and running those tests. I  would be OK helping to set that up but I'd need initial direction.

**Comment by moog16** [comment]
Opened this PR: https://github.com/material-components/material-components-web-react/issues/71. I'm just gonna run the tests locally and merge this for you. Thanks!

**Comment by johnelliott** [comment]
Thanks @moog16

**Pull request merged**
