### PR TITLE
fix(chips, text-field): add null check for foundation (#675)

### PR DESCRIPTION
**Pull request by Markus-Schwer**

### CODE REVIEW

**Comment by Markus-Schwer** [comment]
I signed it!

**Comment by moog16** [comment]
@Markus-Schwer can you update your branch with `rc0.13.0`?

**Comment by moog16** [comment]
fixes https://github.com/material-components/material-components-web-react/pull/862

**Comment by Markus-Schwer** [comment]
Sorry for not responding earlier. I think I messed this PR up. I deleted the fork because I wanted to get a newer version of this repo, as the fork was a bit behind (in hindsight i could have updated my fork with a PR). How about I close this PR and create a new one from `rc0.13.0`?

**Pull request closed without merging**
