### PR TITLE
fix(test): clientHeight unit test

### PR DESCRIPTION
**Pull request by TroyTae**
I originally tried to fix another issue, but there was a problem with the test code.
Height varies depending on browser.
For example, height is "19" in my browser.
So I compare it with real DOM's height.

Please check :)

### CODE REVIEW

**Comment by TroyTae** [comment]
I signed it!

**Comment by moog16** [comment]
@TroyTae can you please merge rc0.10.0 branch into  your branch and push? It'll kick off the tests

**Comment by TroyTae** [comment]
@moog16 
I complete to merge with ```rc0.10.0``` branch.
Should I do this my every PR in the future?

**Comment by moog16** [comment]
@TroyTae yes please merge to the latest rcX.0 branch. Next will be rc0.11.0

**Comment by moog16** [comment]
merged - signed in https://github.com/material-components/material-components-web-react/pull/668#issuecomment-462135646. PR tests passin gin #673

**Pull request merged**
