### PR TITLE
feat(button): Add dense variant to button

### LINKED ISSUE #214: No dense option on button
Button is missing the dense variant!

### PR DESCRIPTION
**Pull request by lucasecdb**
fixes #214

### CODE REVIEW

**Comment by moog16** [comment]
@lucasecdb can you please sign this PR. Also I know you can't run the screenshot test, but could you add a dense screenshot variant to the screenshot tests? Lmk if you need help with running them. You'll need to follow this and install docker https://github.com/material-components/material-components-web-react/blob/master/docs/screenshot-tests.md

**Comment by moog16** [comment]
That looks good! I'll have to manually update the golden.json. Once I get the hash can you update the golden.json file with it?

**Comment by lucasecdb** [comment]
sure!

**Comment by moog16** [comment]
@lucasecdb we're working on updating the screenshot testing framework. I could update accordingly when we merge it in. Can you give me push access to your branch?

**Comment by lucasecdb** [comment]
@moog16 sure, I invited you as a collaborator on my fork

**Comment by moog16** [comment]
Thanks! I'll update as soon as #232 is merged

**Comment by moog16** [comment]
@lucasecdb can you please replace the golden.json line:

```
"button": "a0cf6b2a5d09400657303bb2a7b220dbe33642a8f44fd7571cdfcf5517fb3586",
```

**Comment by lucasecdb** [comment]
@moog16 done!

**Comment by moog16** [comment]
@lucasecdb - for some reason the CLA/google bot is not signed anymore (also don't see you signing this pr). Could you please comment "I signed it"?

**Comment by lucasecdb** [comment]
I signed it

**Comment by moog16** [comment]
Thanks @lucasecdb !!

**Pull request merged**
