### PR TITLE
(fix:ripple) not activating when clicked after touch

### PR DESCRIPTION
**Pull request by Arthie**
[Bug]: Ripple does not activate when clicked if it was previously activated with touch
fixes: #931

### CODE REVIEW

**Comment by moog16** [comment]
How do you reproduce this? I just want to test this.

**Comment by Arthie** [comment]
@moog16 I have a touchscreen laptop makes it easy.
But u can simulate touch events with dev tools when u enable responsive / mobile view.
So to reproduce:
1) go in mobile view with dev tools,  click the button. (this sets the state of `isTouched` to `true`)
2) exit mobile view, click the button again and ripple wont activate. (`isTouched` is never set to `false` again)

**Comment by moog16** [comment]
Change looks good! Could you please add a unit test?

**Comment by Arthie** [comment]
> Change looks good! Could you please add a unit test?

I tried to add the test but after struggling to install the dependencies and when I finally was able to run the tests I got: `(chromium-browser:18737): Gtk-WARNING **: 15:03:11.370: cannot open display:` because the linux environment (WSL) has no gui interface. Really frustrating. I gave up after that not worth spending more time on it.

Hope you understand, I am not able to add tests.

**Comment by moog16** [comment]
@Arthie thanks for trying...I'll add a test and post it here for you to commit. Once that happens let's merge it!

**Comment by Arthie** [comment]
@moog16 Thanks! I have added the test.

**Comment by moog16** [comment]
Arthie you added it to the Button test. It should instead be added to `test/unit/ripple/index.test.tsx`

**Comment by Arthie** [comment]
@moog16 Yea, sorry 😅 fixed it and cleaned the commit history.

**Pull request merged**
