### PR TITLE
fix(menu-surface): remove hoisted element

### PR DESCRIPTION
**Pull request by aluminick**
Remove hoisted element on componentWillUnmount

### CODE REVIEW

**Comment by moog16** [comment]
@aluminick - thanks for doing this! I will review in a bit.

fixes https://github.com/material-components/material-components-web-react/issues/500

**Comment by moog16** [comment]
@aluminick it seems to be working and code looks good. Can you please add unit tests  to support your change?

**Comment by aluminick** [comment]
@moog16 sure. I will add it later today. Thanks

**Comment by aluminick** [comment]
I am working on the test but I came across these error `'Warning: render(...): It looks like the React-rendered content of this container was removed without
using React.`.

**Comment by moog16** [comment]
is that during the test?

**Comment by aluminick** [comment]
Yes it's during the test, it's when I unmount the component. I believe it's because react was not used when hoisted. Anyways, I already posted another issue about menu-surface hoisting. Thanks

**Pull request closed without merging**
