### PR TITLE
fix(line-ripple): Convert style name to camel case

### LINKED ISSUE #86: Bug(Line Ripple): setStyle throws Warning for transform-origin
screen shot 2018-05-31 at 10 23 14

Steps to repro:

1. set `rippleCenter` to another value

Result: throws warning

### PR DESCRIPTION
**Pull request by lucasecdb**
fixes #86

### CODE REVIEW

**Comment by moog16** [comment]
@lucasecdb didn't see this! I also fixed it with a simple `if` statement. See https://github.com/material-components/material-components-web-react/pull/102/.

Could you add a test? Similar to the one in my PR?

**Comment by lucasecdb** [comment]
@moog16 sure!

**Comment by moog16** [comment]
Cool thanks for making that change. I will open another PR so it runs the tests.

**Comment by moog16** [comment]
@lucasecdb can you please sign this PR https://github.com/material-components/material-components-web-react/pull/106

**Comment by moog16** [comment]
Hmm interesting, tests are passing in this PR now. But #106 also is passing. Once you sign this one, we can merge it!

**Comment by lucasecdb** [comment]
@googlebot I give my consent!

**Pull request merged**
