### PR TITLE
Refactor/top app bar/deprecate render props

### LINKED ISSUE #698: Deprecate Top App Bar renderProps
related https://github.com/material-components/material-components-web-react/pull/688

In v0.13.0 deprecate props and methods in top-app-bar/index.ts to support renderProps. This is in favor of compositional declaration of the TopAppBar.

### PR DESCRIPTION
**Pull request by mgr34**
successful merge should close #698.

---

I signed it.

### CODE REVIEW

**Comment by moog16** [comment]
Please update with rc0.14.0 branch

**Comment by moog16** [comment]
@mgr34 I updated rc0.14.0 again. Sorry you will need to push another update

**Comment by mgr34** [comment]
@moog16 no problem. All set. :)

**Comment by moog16** [comment]
Thanks!

**Comment by moog16** [comment]
signed in https://github.com/material-components/material-components-web-react/pull/915#issue-285863279

**Pull request merged**
