### PR TITLE
chore(ripple): Add displayName

### PR DESCRIPTION
**Pull request by ockham**
Add a `displayName` of `WithRipple(WrappedComponent)` to ripple, following [React Convention](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging).

This might help getting MDC React components to work in [Calypso](https://github.com/Automattic/wp-calypso)'s [devdocs](https://wpcalypso.wordpress.com/devdocs/design).

/cc @lynnjepsen @aduth @blowery @nb

### CODE REVIEW

**Comment by moog16** [comment]
Looks good! Took screenshot of it working: 

screenshot from 2018-07-31 12-42-56

Thanks for filing. I will open a subsequent PR to run tests. @ockham can you please sign this PR? You just need to comment "I signed it!"

**Comment by moog16** [comment]
Created this PR: https://github.com/material-components/material-components-web-react/pull/196.

When tests pass on #196, we can merge this one.

**Comment by moog16** [comment]
#196 passing - @ockham please sign it, and I'll merge once we're squared away.

**Comment by ockham** [comment]
Thanks for reviewing @moog16, and apologies for the late reply! I'm checking with our legal dept on the CLA to make sure it's okay to sign it...

**Comment by ockham** [comment]
I signed it!

Actually, Automattic has signed a Google CLA before, so I only had to be added to the relevant group :slightly_smiling_face:

**Comment by moog16** [comment]
Great! Thanks :) I'm not sure why the cla isn't passing right now, but the tests passed in the #196, so I think I can just merge it.

**Pull request merged**
