### PR TITLE
fix(text-field) fix example compilation issue

### PR DESCRIPTION
**Pull request by ZeJ0hn**
The current code doesn't compile.
Need to use currentTarget instead of target (because target is generic now)

### CODE REVIEW

**Comment by moog16** [comment]
@ZeJ0hn please sign the PR

**Comment by ZeJ0hn** [comment]
Sign ? the CLA ?
Already sign normally.

If no, what do I forgot ?

**Comment by moog16** [comment]
Just need to comment "I signed it"

**Comment by ZeJ0hn** [comment]
I signed it

**Comment by moog16** [comment]
Thanks!

**Pull request merged**
