### PR TITLE
fix(fab): Made initRipple and unbounded props optional

### PR DESCRIPTION
**Pull request by Maxim-Mazurok**
This PR is a follow up to this conversation: https://github.com/material-components/material-components-web-react/commit/b62c36fbcee3e6aecab00ca949a93080f4254719#r33164756

`initRipple` and `unbounded` props should be optional.

### CODE REVIEW

**Comment by moog16** [comment]
@Maxim-Mazurok it looks like tests are failing. Could you please provide a fix for those? Thanks!

**Comment by Maxim-Mazurok** [comment]
I thought that tests failed because the previous build also failed. I will run tests locally later to figure out what happened.

**Comment by moog16** [comment]
https://travis-ci.com/material-components/material-components-web-react/jobs/193054458

It looks like you're getting TS FabProp errors.

Sounds good - thanks!

**Comment by moog16** [comment]
fixes #841

**Comment by Maxim-Mazurok** [comment]
Sorry for leaving this PR without updates for a while.
I took a look and it seems that this change is not as easy as I thought originally, it breaks a lot of stuff. Needs further investigation, so I'll try to find time for it in the next couple of days.

**Comment by moog16** [comment]
@Maxim-Mazurok no worries - thanks for making the changes. LMK if you need anything.

**Comment by moog16** [comment]
@Maxim-Mazurok there are a few conflicts occurring now. Please update when you get a chance. Thanks!

**Pull request closed without merging**
