### PR TITLE
(fix) Windows development

### PR DESCRIPTION
**Pull request by madaz**
Enable development on windows environment.

Replace non-windows commands for npm cross environment packages.

* `rimraf` replaces the `rm` command
* `cross-env` for setting environment variables

@moog16

### CODE REVIEW

**Comment by madaz** [comment]
I did not test the screenshots on Docker, the changes made were to get the
`npm run test:unit` to work first

I ran into other problems when trying to get this project setup on my
windows machine. `npm install/ci` is failing as well.  I can log an issue
for that if you want.

**Comment by moog16** [comment]
gotcha - nope this is better than nothing :)

**Comment by moog16** [comment]
tests pr https://github.com/material-components/material-components-web-react/pull/664

**Comment by moog16** [comment]
@madaz  please sign this PR

**Comment by madaz** [comment]
I signed it!

**Pull request merged**
