### PR TITLE
feature(top-app-bar): permit otherProps

### PR DESCRIPTION
**Pull request by TroyTae**
I can see most of components permit otherProps.
If there is any special reason I want permit otherProps in the top-app-bar too.
Thank you for read :)

### CODE REVIEW

**Comment by TroyTae** [comment]
@moog16 
I can see you're having same problem when Travis CI process.
Do you know what is this?
https://travis-ci.com/material-components/material-components-web-react/jobs/153656980

**Comment by moog16** [comment]
Its not you its me... ;) 

One of the contributors has to kick off the screenshot tests. The process is as follows:

```
1. contributor reviews PR
2. collaborate until final code review
3. contributor updates golden.json screenshots (if necessary)
4. contributor opens separate PR to run screenshot tests
5. merge if all the above pass the test
```

**Comment by moog16** [comment]
@TroyTae could you add a few unit tests of different attributes being passed through the top app bar?

**Comment by TroyTae** [comment]
@moog16 
I didn't write unit test code because already there is test code using "otherProps".
(https://github.com/material-components/material-components-web-react/blob/master/test/unit/top-app-bar/index.test.js#L22)
Hmm... Is there anything I have misunderstood??

**Comment by moog16** [comment]
@TroyTae what you linked to is specifically for actionItem. You added logic for the top app bar element.

**Comment by TroyTae** [comment]
@moog16 
I got it!
Thank you for your help 👍

**Comment by moog16** [comment]
@TroyTae looks like tests are passing, but you need to sign it. Please comment "I signed it!"

**Comment by TroyTae** [comment]
I signed it!

**Comment by moog16** [comment]
Tests are passing in https://github.com/material-components/material-components-web-react/pull/372. Merging!

**Pull request merged**
